/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { VgrButtonVariant } from "./components/vgr-button/vgr-button";
export { VgrButtonVariant } from "./components/vgr-button/vgr-button";
export namespace Components {
    interface VgrButton {
        /**
          * @default false
         */
        "disabled": boolean;
        "icon"?: string;
        "text": string;
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant": VgrButtonVariant;
    }
    interface VgrIcon {
        /**
          * SVG markup for the icon. Must come from our own icon package, never from user input, since it is rendered with innerHTML.
         */
        "icon": string;
    }
}
export interface VgrButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVgrButtonElement;
}
declare global {
    interface HTMLVgrButtonElementEventMap {
        "vgrClick": void;
    }
    interface HTMLVgrButtonElement extends Components.VgrButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVgrButtonElementEventMap>(type: K, listener: (this: HTMLVgrButtonElement, ev: VgrButtonCustomEvent<HTMLVgrButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVgrButtonElementEventMap>(type: K, listener: (this: HTMLVgrButtonElement, ev: VgrButtonCustomEvent<HTMLVgrButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVgrButtonElement: {
        prototype: HTMLVgrButtonElement;
        new (): HTMLVgrButtonElement;
    };
    interface HTMLVgrIconElement extends Components.VgrIcon, HTMLStencilElement {
    }
    var HTMLVgrIconElement: {
        prototype: HTMLVgrIconElement;
        new (): HTMLVgrIconElement;
    };
    interface HTMLElementTagNameMap {
        "vgr-button": HTMLVgrButtonElement;
        "vgr-icon": HTMLVgrIconElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    interface VgrButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "icon"?: string;
        "onVgrClick"?: (event: VgrButtonCustomEvent<void>) => void;
        "text": string;
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant"?: VgrButtonVariant;
    }
    interface VgrIcon {
        /**
          * SVG markup for the icon. Must come from our own icon package, never from user input, since it is rendered with innerHTML.
         */
        "icon": string;
    }

    interface VgrButtonAttributes {
        "variant": VgrButtonVariant;
        "disabled": boolean;
        "type": 'button' | 'submit' | 'reset';
        "text": string;
        "icon": string;
    }
    interface VgrIconAttributes {
        "icon": string;
    }

    interface IntrinsicElements {
        "vgr-button": Omit<VgrButton, keyof VgrButtonAttributes> & { [K in keyof VgrButton & keyof VgrButtonAttributes]?: VgrButton[K] } & { [K in keyof VgrButton & keyof VgrButtonAttributes as `attr:${K}`]?: VgrButtonAttributes[K] } & { [K in keyof VgrButton & keyof VgrButtonAttributes as `prop:${K}`]?: VgrButton[K] } & OneOf<"text", VgrButton["text"], VgrButtonAttributes["text"]>;
        "vgr-icon": Omit<VgrIcon, keyof VgrIconAttributes> & { [K in keyof VgrIcon & keyof VgrIconAttributes]?: VgrIcon[K] } & { [K in keyof VgrIcon & keyof VgrIconAttributes as `attr:${K}`]?: VgrIconAttributes[K] } & { [K in keyof VgrIcon & keyof VgrIconAttributes as `prop:${K}`]?: VgrIcon[K] } & OneOf<"icon", VgrIcon["icon"], VgrIconAttributes["icon"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vgr-button": LocalJSX.IntrinsicElements["vgr-button"] & JSXBase.HTMLAttributes<HTMLVgrButtonElement>;
            "vgr-icon": LocalJSX.IntrinsicElements["vgr-icon"] & JSXBase.HTMLAttributes<HTMLVgrIconElement>;
        }
    }
}
