/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { VgrButtonVariant } from "./components/vgr-button/vgr-button";
export { VgrButtonVariant } from "./components/vgr-button/vgr-button";
export namespace Components {
    interface VgrButton {
        /**
          * Disables the button and prevents the click event from firing.
          * @default false
         */
        "disabled": boolean;
        /**
          * Native button type — matters when the button sits inside a <form>.
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Visual style of the button.
          * @default 'primary'
         */
        "variant": VgrButtonVariant;
    }
}
export interface VgrButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLVgrButtonElement;
}
declare global {
    interface HTMLVgrButtonElementEventMap {
        "vgrClick": void;
    }
    interface HTMLVgrButtonElement extends Components.VgrButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLVgrButtonElementEventMap>(type: K, listener: (this: HTMLVgrButtonElement, ev: VgrButtonCustomEvent<HTMLVgrButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLVgrButtonElementEventMap>(type: K, listener: (this: HTMLVgrButtonElement, ev: VgrButtonCustomEvent<HTMLVgrButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLVgrButtonElement: {
        prototype: HTMLVgrButtonElement;
        new (): HTMLVgrButtonElement;
    };
    interface HTMLElementTagNameMap {
        "vgr-button": HTMLVgrButtonElement;
    }
}
declare namespace LocalJSX {
    interface VgrButton {
        /**
          * Disables the button and prevents the click event from firing.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Emitted when the button is clicked (and not disabled).
         */
        "onVgrClick"?: (event: VgrButtonCustomEvent<void>) => void;
        /**
          * Native button type — matters when the button sits inside a <form>.
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Visual style of the button.
          * @default 'primary'
         */
        "variant"?: VgrButtonVariant;
    }

    interface VgrButtonAttributes {
        "variant": VgrButtonVariant;
        "disabled": boolean;
        "type": 'button' | 'submit' | 'reset';
    }

    interface IntrinsicElements {
        "vgr-button": Omit<VgrButton, keyof VgrButtonAttributes> & { [K in keyof VgrButton & keyof VgrButtonAttributes]?: VgrButton[K] } & { [K in keyof VgrButton & keyof VgrButtonAttributes as `attr:${K}`]?: VgrButtonAttributes[K] } & { [K in keyof VgrButton & keyof VgrButtonAttributes as `prop:${K}`]?: VgrButton[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "vgr-button": LocalJSX.IntrinsicElements["vgr-button"] & JSXBase.HTMLAttributes<HTMLVgrButtonElement>;
        }
    }
}
