'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

import { type VgrButtonCustomEvent } from "@vgregion/components-core";
import type { Components } from "@vgregion/components-core/dist/components";
import { VgrButton as VgrButtonElement, defineCustomElement as defineVgrButton } from "@vgregion/components-core/dist/components/vgr-button.js";

export type VgrButtonEvents = { onVgrClick: EventName<VgrButtonCustomEvent<void>> };

export const VgrButton: StencilReactComponent<VgrButtonElement, VgrButtonEvents, Components.VgrButton> = /*@__PURE__*/ createComponent<VgrButtonElement, VgrButtonEvents, Components.VgrButton>({
    tagName: 'vgr-button',
    elementClass: VgrButtonElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: { onVgrClick: 'vgrClick' } as VgrButtonEvents,
    defineCustomElement: defineVgrButton
});
